### PR TITLE
LD 2016 Logo?

### PR DESCRIPTION
**Pull request by theTechnoKid**
Hey I made a logo for Ludum Dare. Try and see if it works. I used a free font called TeX Gyre Cursor. Also if you need any help on anything else, I would love to see what I can do. (I need to freshen up my PHP though :) )

### CODE REVIEW

**Comment by theTechnoKid** [comment]
I can send you the Photoshop files if you want.

**Comment by theTechnoKid** [comment]
Maybe you cud try it on the new site.

**Comment by mkalam-alami** [comment]
I don't think that's the kind of contribution PoV was expecting :-P You can't just submit a new logo like that, how would the community react if the logo was changed out the the blue? Plus I actually prefer the current logo...

It's a good thing you want to help with a website, but my suggestion would be to take a look at the existing issues instead. Or maybe wait for the new version to take shape and contribute to that one.

**Comment by theTechnoKid** [comment]
Ok sorry I'll look at the issues :P

**Pull request closed without merging**
